# Generated by Django 4.0.6 on 2022-08-23 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='board_name',
        ),
    ]
