# Generated by Django 3.2.14 on 2022-08-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_count',
            field=models.CharField(default='', max_length=10),
        ),
    ]
