# Generated by Django 3.2.14 on 2022-08-23 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_user_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_count',
        ),
    ]
