# Generated by Django 3.2.14 on 2022-10-06 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_count', models.CharField(max_length=10, null=True, verbose_name='스쿼트 개수')),
                ('user_dt', models.DateField(auto_now_add=True, null=True, verbose_name='스쿼트 챌린지 시작시간')),
                ('user_confirm', models.BooleanField(default=False)),
                ('user_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='로그인 유저')),
            ],
            options={
                'ordering': ('-user_dt',),
            },
        ),
    ]
