# Generated by Django 3.2.14 on 2022-08-23 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Count_Post',
        ),
    ]
