# Generated by Django 3.2.14 on 2022-08-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='count_post',
            name='user_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
