# Generated by Django 3.2.14 on 2022-08-24 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_alter_count_post_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='count_post',
            name='user_confirm',
        ),
    ]
