# Generated by Django 3.2.14 on 2022-09-15 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_nav_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='TITLE')),
                ('description', models.TextField(verbose_name='item description')),
                ('item_category', models.CharField(choices=[('1', '운동기구'), ('2', '운동화'), ('3', '운동복'), ('4', '보조식품'), ('5', '기타')], max_length=20)),
                ('user_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='로그인 유저')),
            ],
        ),
    ]
