# Generated by Django 3.2.14 on 2022-10-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='liked_users',
            field=models.ManyToManyField(related_name='liked_posts', to='users.Profile'),
        ),
    ]
