# Generated by Django 4.1.1 on 2022-10-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20220920_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_category',
            field=models.CharField(choices=[('운동기구', '운동기구'), ('운동화', '운동화'), ('운동복', '운동복'), ('보조식품', '보조식품'), ('기타', '기타')], max_length=20),
        ),
    ]
