# Generated by Django 3.2.14 on 2022-10-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_item_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='images',
            field=models.FileField(default=None, upload_to='market_item/%Y/%m/%d/'),
        ),
    ]
