# Generated by Django 3.2.14 on 2022-10-05 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_item_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default=None, upload_to='market_item/%Y/%m/%d/')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.upload_img'),
        ),
    ]
