# Generated by Django 3.2.14 on 2022-10-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20221006_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='images',
        ),
        migrations.AddField(
            model_name='item',
            name='img1',
            field=models.FileField(default=None, upload_to='market_item/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='item',
            name='img2',
            field=models.FileField(default=None, upload_to='market_item/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='item',
            name='img3',
            field=models.FileField(default=None, upload_to='market_item/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='Upload_img',
        ),
    ]
