# Generated by Django 3.2.14 on 2022-10-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20221006_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(verbose_name='물품 설명'),
        ),
        migrations.AlterField(
            model_name='item',
            name='img1',
            field=models.FileField(default=None, upload_to='market_item/%Y/%m/%d/', verbose_name='물품 이미지'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_category',
            field=models.CharField(choices=[('운동기구', '운동기구'), ('운동화', '운동화'), ('운동복', '운동복'), ('보조식품', '보조식품'), ('기타', '기타')], max_length=20, verbose_name='물품 종류'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=30, verbose_name='물품 제목'),
        ),
    ]
