# Generated by Django 3.2.14 on 2022-10-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auth_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_number', models.IntegerField(verbose_name='인증번호')),
            ],
        ),
        migrations.CreateModel(
            name='nav_user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('user_id', models.CharField(max_length=32, unique=True, verbose_name='유저 아이디')),
                ('user_name', models.CharField(max_length=16, verbose_name='유저 이름')),
                ('user_email', models.EmailField(max_length=128, verbose_name='유저 이메일')),
            ],
            options={
                'verbose_name': '네이버 로그인 유저',
                'verbose_name_plural': '네이버 로그인 유저',
                'db_table': 'nav_user',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('user_id', models.CharField(max_length=32, unique=True, verbose_name='유저 아이디')),
                ('user_pw', models.CharField(max_length=128, verbose_name='유저 비밀번호')),
                ('user_name', models.CharField(max_length=16, verbose_name='유저 이름')),
                ('user_email', models.EmailField(max_length=128, verbose_name='유저 이메일')),
                ('user_sex', models.CharField(max_length=16, verbose_name='유저 성별')),
                ('user_birth', models.CharField(max_length=16, verbose_name='유저 생일')),
                ('user_register_dttm', models.DateField(auto_now_add=True, verbose_name='계정 생성시간')),
                ('user_image', models.ImageField(blank=True, null=True, unique=True, upload_to='profile_image/', verbose_name='프로필사진')),
                ('user_background', models.ImageField(blank=True, null=True, unique=True, upload_to='profile_image/', verbose_name='배경사진')),
            ],
            options={
                'verbose_name': '유저',
                'verbose_name_plural': '유저',
                'db_table': 'profile',
            },
        ),
    ]
