# Generated by Django 4.0.6 on 2022-08-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_user_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_email',
            field=models.EmailField(max_length=128, verbose_name='유저 이메일'),
        ),
    ]
