# Generated by Django 4.1.1 on 2022-10-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_nav_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(blank=True, unique=True, upload_to='profile_image/', verbose_name='프로필사진'),
        ),
    ]
