# Generated by Django 4.0.7 on 2022-08-23 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='board_name',
        ),
    ]
