# Generated by Django 4.0.7 on 2022-08-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_remove_board_board_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='board_name',
            field=models.CharField(default='Python', max_length=32, verbose_name='게시판 종류'),
        ),
    ]
